
language: cpp

compiler:
- gcc
- clang

before_install:
  - cmake --version

script:
  - mkdir build && cd build && cmake -DTESTS=1 .. && cmake --build . --target Experimental

env:
  global:
  - LANG="en_US.UTF-8"

os:
- linux
- osx
