############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Bernardo Gabriel                                                 #
############################################################################

[Include common/imc-addresses.ini]

[General]
Vehicle                                                 = doris

############################################################################
# Actuators.                                                               #
############################################################################

[Actuators.WASABi]
Enabled                                                 = Hardware
Entity Label                                            = WASABi
Debug Level                                             = None
IO Port - Device                                        = uart:///dev/ttyAMA0:19200
Output Data Rate                                        = 1.0
Power Channel 0 - Name                                  = RPi
Power Channel 0 - State                                 = 1
Power Channel 1 - Name                                  = IDX56
Power Channel 1 - State                                 = 0
Power Channel 2 - Name                                  = PUMP1
Power Channel 2 - State                                 = 0
Power Channel 3 - Name                                  = PUMP2
Power Channel 3 - State                                 = 0
Power Channel 4 - Name                                  = PUMP3
Power Channel 4 - State                                 = 0
Power Channel 5 - Name                                  = PUMP4
Power Channel 5 - State                                 = 0
Power Channel 6 - Name                                  = PUMP5
Power Channel 6 - State                                 = 0
Power Channel 7 - Name                                  = 5V_0
Power Channel 7 - State                                 = 0
Water Level 1 - GPIO Label                              = WL1
Water Level 2 - GPIO Label                              = WL2
Water Flow 1 - Entity Label                             = WF1
Water Flow 2 - Entity Label                             = WF2
Water Level Sensors Warnings                            = false
OSLO - Entity Label                                     = OSLO

[Actuators.WASABi::OSLO]
Valve 0 - Name                                          = VALVE1
Valve 0 - State                                         = false
Valve 1 - Name                                          = VALVE2
Valve 1 - State                                         = false
Valve 2 - Name                                          = VALVE3
Valve 2 - State                                         = false
Endpoint 1 - Label                                      = EP0
Endpoint 2 - Label                                      = EP1
Step Id                                                 = 3

[Actuators.IDX56]
Enabled                                                 = Hardware
Entity Label                                            = IDX56
Debug Level                                             = None
Power Channel Name                                      = IDX56
Node Id                                                 = 1
Device                                                  = EPOS4
Protocol                                                = CANopen
Interface                                               = CAN_mcp251x 0
Port                                                    = CAN0
Baudrate                                                = 1000000
Mode                                                    = Velocity
Maximum RPM                                             = 1000
Actuator Id                                             = 2

############################################################################
# Monitors.                                                                #
############################################################################

[Monitors.HostResources]
Enabled                                                 = Always
Entity Label                                            = Host Resources
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Active                                                  = true

############################################################################
# Payload.                                                                 #
############################################################################

[Payload.Doris]
Enabled                                                 = Hardware
Entity Label                                            = Doris
Debug Level                                             = None
Active                                                  = true
Motor Entity Label                                      = IDX56
Motor Id                                                = 2
Step Motor Id                                           = 3
Minimum Water Level - GPIO Label                        = WL1
Maximum Water Level - GPIO Label                        = WL2
Water Flow 1 - Entity Label                             = WF1
Water Flow 2 - Entity Label                             = WF2
Endpoint 1 - GPIO Label                                 = EP0
Endpoint 2 - GPIO Label                                 = EP1
Pump 1 - Power Channel Name                             = PUMP1
Pump 2 - Power Channel Name                             = PUMP2
Pump 3 - Power Channel Name                             = PUMP3
Pump 4 - Power Channel Name                             = PUMP4
Pump 5 - Power Channel Name                             = PUMP5
Valve 1 - Power Channel Name                            = VALVE1
Valve 2 - Power Channel Name                            = VALVE2
Valve 3 - Power Channel Name                            = VALVE3

############################################################################
# Supervisors.                                                             #
############################################################################

[Supervisors.Power]
Enabled                                                 = Hardware
Entity Label                                            = Power Supervisor
Main Power Channel                                      = System
Command - On Power Down                                 = systemctl poweroff
Command - On Power Down Abort                           = 

############################################################################
# Transports.                                                              #
############################################################################

[Transports.Announce]
Enabled                                                 = Always
Entity Label                                            = Service Announcer
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Execution Priority                                      = 10
Announcement Periodicity                                = 10
Enable Loopback                                         = 1
Enable Multicast                                        = 1
Enable Broadcast                                        = 1
Multicast Address                                       = 224.0.75.69
Ports                                                   = 30100, 30101, 30102, 30103, 30104
Ignored Interfaces                                      = 

[Transports.TCP.Client]
Enabled                                                 = Hardware
Entity Label                                            = TCP to Master
Server - Address                                        = 10.0.11.20
Server - Port                                           = 9999
Trace - Incoming Messages                               = false
Trace - Outgoing Messages                               = false
Transports                                              = EntityState,
                                                          EntityActivationState,
                                                          EntityInfo,
                                                          EntityParameters,
                                                          LogBookEntry,
                                                          SamplingAction
Loopback Internal Messages                              = false

[Transports.HTTP]
Enabled                                                 = Always
Entity Label                                            = HTTP Server
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Execution Priority                                      = 10
Port                                                    = 8080
Threads                                                 = 5
Transports                                              = CpuUsage,
                                                          Current,
                                                          EntityState,
                                                          Temperature,
                                                          Voltage,
                                                          EntityList

[Transports.Logging]
Enabled                                                 = Always
Entity Label                                            = Logger
Debug Level                                             = None
Activation Time                                         = 0
Deactivation Time                                       = 0
Execution Priority                                      = 2
Flush Interval                                          = 5
LSF Compression Method                                  = gzip
LSF Volume Size                                         = 0
Transports                                              = CpuUsage,
                                                          EntityActivationState,
                                                          EntityList,
                                                          EntityMonitoringState,
                                                          EntityParameters,
                                                          EntityState,
                                                          EstimatedState,
                                                          GpsFix,
                                                          Heartbeat,
                                                          LogBookEntry,
                                                          PowerChannelControl,
                                                          PowerChannelState,
                                                          QueryEntityParameters,
                                                          SaveEntityParameters,
                                                          Temperature


