############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Bernardo Gabriel                                                 #
############################################################################

[Include common/imc-addresses.ini]

[General]
Vehicle                                                 = redx

############################################################################
# Payload.                                                                 #
############################################################################

[Monitors.HostResources]
Enabled                                                 = Always
Entity Label                                            = Host Resources
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Active                                                  = true

############################################################################
# Payload.                                                                 #
############################################################################

[Payload.RedX]
Enabled                                                 = Always
Active                                                  = true
Entity Label                                            = RedX
Debug Level                                             = None
Activation Time                                         = 1
Deactivation Time                                       = 1
Motor - Id                                              = 0
Motor - Actuation                                       = 10
Water Pump - Id                                         = 1
Water Pump - Actuation                                  = 100
Water Pump - Depth                                      = 10
Water Pump - Entity Label                               = Water Pump
Tank Pump - Power Channel Name                          = Press Pump
Maximum Water Level - GPIO Name                         = Water Level Max
Minimum Water Level - GPIO Name                         = Water Level Min
Purge Valve - Power Channel Name                        = Purge Valve
Purge Valve Operation Timeout                           = 3
Filter 0 - Power Channel Name                           = Filter 0
Filter 1 - Power Channel Name                           = Filter 1
Filter 2 - Power Channel Name                           = Filter 2
Filter 3 - Power Channel Name                           = Filter 3
Filter 4 - Power Channel Name                           = Filter 4
Filter 5 - Power Channel Name                           = Filter 5
Filter 6 - Power Channel Name                           = Filter 6
Filter 7 - Power Channel Name                           = Filter 7
Filter 8 - Power Channel Name                           = Filter 8
Filters Water Flow - Entity Label                       = Filters Water Flow
Number of Filters to Use                                = 1
Last Filter Used                                        = -1
Filter Fill Up Timeout                                  = 3
Restart Allowed                                         = false
Pause Allowed                                           = false

############################################################################
# Power.                                                                   #
############################################################################

[Power.OREO]
Enabled                                                 = Hardware
Entity Label                                            = Oreo
Debug Level                                             = None
IO Port - Device                                        = uart:///dev/ttyAMA1:19200
Power Channel 0 - Name                                  = FAN
Power Channel 0 - State                                 = true
Power Channel 1 - Name                                  = Filter 0
Power Channel 1 - State                                 = false
Power Channel 2 - Name                                  = Filter 1
Power Channel 2 - State                                 = false
Power Channel 3 - Name                                  = Filter 2
Power Channel 3 - State                                 = false
Power Channel 4 - Name                                  = Filter 3
Power Channel 4 - State                                 = false
Power Channel 5 - Name                                  = Filter 4
Power Channel 5 - State                                 = false
Power Channel 6 - Name                                  = Filter 5
Power Channel 6 - State                                 = false
Power Channel 7 - Name                                  = Filter 6
Power Channel 7 - State                                 = false
Power Channel 8 - Name                                  = Filter 7
Power Channel 8 - State                                 = false
Power Channel 9 - Name                                  = Filter 8
Power Channel 9 - State                                 = false
Power Channel 10 - Name                                 = Purge Valve
Power Channel 10 - State                                = false
Output Data Rate                                        = 1

[Power.PARSEC]
Enabled                                                 = Always
Entity Label                                            = Parsec
Debug Level                                             = None
IO Port - Device                                        = uart:///dev/ttyAMA0:19200
Output Data Rate                                        = 1
Power Channel 0 - Name                                  = Private (RPI)
Power Channel 0 - State                                 = true
Power Channel 1 - Name                                  = Private (ETH)
Power Channel 1 - State                                 = false
Power Channel 2 - Name                                  = Private (WIFI)
Power Channel 2 - State                                 = false
Power Channel 3 - Name                                  = Press Pump
Power Channel 3 - State                                 = false
Water Pump - Id                                         = 0
Water Pump - Entity Label                               = Water Pump
Water Pump - Min Depth                                  = 0.0
Water Pump - Max Depth                                  = 10.0
Motor - Id                                              = 1
Motor - Entity Label                                    = Motor
Water Level 1 - GPIO Label                              = Water Level Max
Water Level 2 - GPIO Label                              = Water Level Min
Water Flow 1 - Entity Label                             = Filters Water Flow
Use Motor Motion for Water Pump Depth                   = true
Water Pump Motion Timeout                               = 15.0

############################################################################
# Supervisors.                                                             #
############################################################################

[Supervisors.Power]
Enabled                                                 = Hardware
Entity Label                                            = Power Supervisor
Main Power Channel                                      = System
Command - On Power Down                                 = systemctl poweroff
Command - On Power Down Abort                           = 

############################################################################
# Transports.                                                              #
############################################################################

[Transports.TCP.Client]
Enabled                                                 = Hardware
Entity Label                                            = TCP to Master
Server - Address                                        = 10.0.11.10
Server - Port                                           = 9999
Trace - Incoming Messages                               = false
Trace - Outgoing Messages                               = false
Transports                                              = EntityState,
                                                          EntityActivationState,
                                                          EntityInfo,
                                                          EntityParameters,
                                                          Heartbeat,
                                                          LogBookEntry,
                                                          LoggingControl,
                                                          Temperature
Loopback Internal Messages                              = true

[Transports.HTTP]
Enabled                                                 = Always
Entity Label                                            = HTTP Server
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Execution Priority                                      = 10
Port                                                    = 8080
Threads                                                 = 5
Transports                                              = CpuUsage,
                                                          Current,
                                                          EntityState,
                                                          Temperature,
                                                          Voltage,
                                                          EntityList

[Transports.Logging]
Enabled                                                 = Always
Entity Label                                            = Logger
Debug Level                                             = None
Activation Time                                         = 0
Deactivation Time                                       = 0
Execution Priority                                      = 2
Flush Interval                                          = 5
LSF Compression Method                                  = gzip
LSF Volume Size                                         = 0
Transports                                              = CpuUsage,
                                                          EntityActivationState,
                                                          EntityList,
                                                          EntityMonitoringState,
                                                          EntityParameters,
                                                          EntityState,
                                                          EstimatedState,
                                                          GpsFix,
                                                          Heartbeat,
                                                          LogBookEntry,
                                                          PowerChannelControl,
                                                          PowerChannelState,
                                                          QueryEntityParameters,
                                                          SaveEntityParameters,
                                                          Temperature
