; [Include ../common/transports.ini]

[Tutorials.TempProd]
Enabled = Always
Entity Label = Producer
Debug Level = Spew
Starting Temperature = 21.0

[Transports.Logging]
Enabled = Always
Entity Label = Logger
Transports = Temperature, EntityList