############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Bernardo Gabriel                                                 #
############################################################################

[Include common/imc-addresses.ini]

[General]
Vehicle                                                 = whitex

############################################################################
# Actuators.                                                               #
############################################################################

[Actuators.WOREO]
Enabled                                                 = Hardware
Entity Label                                            = WOREO
Debug Level                                             = None
IO Port - Device                                        = uart:///dev/ttyAMA0:19200
Output Data Rate                                        = 1.0
Power Channel 0 - Name                                  = VALVE1
Power Channel 0 - State                                 = 0
Power Channel 1 - Name                                  = VALVE2
Power Channel 1 - State                                 = 0
Power Channel 2 - Name                                  = VALVE3
Power Channel 2 - State                                 = 0
Power Channel 3 - Name                                  = VALVE4
Power Channel 3 - State                                 = 0
Power Channel 4 - Name                                  = VALVE5
Power Channel 4 - State                                 = 0
Power Channel 5 - Name                                  = VALVE6
Power Channel 5 - State                                 = 0
Power Channel 6 - Name                                  = VALVE7
Power Channel 6 - State                                 = 0
Power Channel 7 - Name                                  = VALVE8
Power Channel 7 - State                                 = 0
Power Channel 8 - Name                                  = VALVE9
Power Channel 8 - State                                 = 0
Power Channel 9 - Name                                  = VALVE10
Power Channel 9 - State                                 = 0
Power Channel 10 - Name                                 = Fan
Power Channel 10 - State                                = 0
Water Level 1 - GPIO Label                              = WL1
Water Level 2 - GPIO Label                              = WL2
Water Flow - Entity Label                               = WF
Water Level Sensors Warnings                            = false

############################################################################
# Monitors.                                                                #
############################################################################

[Monitors.HostResources]
Enabled                                                 = Always
Entity Label                                            = Host Resources
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Active                                                  = true

############################################################################
# Payload.                                                                 #
############################################################################

[Payload.WhiteX]
Enabled                                                 = Hardware
Entity Label                                            = WhiteX
Debug Level                                             = None
Active                                                  = true
Valve 1 - Power Channel Name                            = VALVE1
Valve 2 - Power Channel Name                            = VALVE2
Valve 3 - Power Channel Name                            = VALVE3
Valve 4 - Power Channel Name                            = VALVE4
Valve 5 - Power Channel Name                            = VALVE5
Valve 6 - Power Channel Name                            = VALVE6
Valve 7 - Power Channel Name                            = VALVE7
Valve 8 - Power Channel Name                            = VALVE8
Valve 9 - Power Channel Name                            = VALVE9
Valve 10 - Power Channel Name                           = VALVE10
Minimum Water Level - GPIO Label                        = WL1
Maximum Water Level - GPIO Label                        = WL2
Water Flow - Entity Label                               = WF

############################################################################
# Supervisors.                                                             #
############################################################################

[Supervisors.Power]
Enabled                                                 = Hardware
Entity Label                                            = Power Supervisor
Main Power Channel                                      = System
Command - On Power Down                                 = systemctl poweroff
Command - On Power Down Abort                           = 

############################################################################
# Transports.                                                              #
############################################################################

[Transports.Announce]
Enabled                                                 = Always
Entity Label                                            = Service Announcer
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Execution Priority                                      = 10
Announcement Periodicity                                = 10
Enable Loopback                                         = 1
Enable Multicast                                        = 1
Enable Broadcast                                        = 1
Multicast Address                                       = 224.0.75.69
Ports                                                   = 30100, 30101, 30102, 30103, 30104
Ignored Interfaces                                      = 

[Transports.TCP.Client]
Enabled                                                 = Hardware
Entity Label                                            = TCP to Master
Server - Address                                        = 10.0.11.20
Server - Port                                           = 9999
Trace - Incoming Messages                               = false
Trace - Outgoing Messages                               = false
Transports                                              = EntityState,
                                                          EntityActivationState,
                                                          EntityInfo,
                                                          EntityParameters,
                                                          LogBookEntry,
                                                          SamplingAction
Loopback Internal Messages                              = false

[Transports.HTTP]
Enabled                                                 = Always
Entity Label                                            = HTTP Server
Activation Time                                         = 0
Deactivation Time                                       = 0
Debug Level                                             = None
Execution Priority                                      = 10
Port                                                    = 8080
Threads                                                 = 5
Transports                                              = CpuUsage,
                                                          Current,
                                                          EntityState,
                                                          Temperature,
                                                          Voltage,
                                                          EntityList

[Transports.Logging]
Enabled                                                 = Always
Entity Label                                            = Logger
Debug Level                                             = None
Activation Time                                         = 0
Deactivation Time                                       = 0
Execution Priority                                      = 2
Flush Interval                                          = 5
LSF Compression Method                                  = gzip
LSF Volume Size                                         = 0
Transports                                              = CpuUsage,
                                                          EntityActivationState,
                                                          EntityList,
                                                          EntityMonitoringState,
                                                          EntityParameters,
                                                          EntityState,
                                                          EstimatedState,
                                                          GpsFix,
                                                          Heartbeat,
                                                          LogBookEntry,
                                                          PowerChannelControl,
                                                          PowerChannelState,
                                                          QueryEntityParameters,
                                                          SaveEntityParameters,
                                                          Temperature


