############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Bernardo Gabriel                                                 #
############################################################################
# Example configuration for OREO power management system                   #
############################################################################

[Power.OREO]
Enabled                                             = Always
Entity Label                                        = Oreo
Debug Level                                         = None
IO Port - Device                                    = uart:///dev/ttyUSB1:19200
Power Channel 0 - Name                              = FAN
Power Channel 0 - State                             = true
Power Channel 1 - Name                              = Valve 1
Power Channel 1 - State                             = false
Power Channel 2 - Name                              = Valve 2
Power Channel 2 - State                             = false
Power Channel 3 - Name                              = Valve 3
Power Channel 3 - State                             = false
Power Channel 4 - Name                              = Valve 4
Power Channel 4 - State                             = false
Power Channel 5 - Name                              = Valve 5
Power Channel 5 - State                             = false
Power Channel 6 - Name                              = Valve 6
Power Channel 6 - State                             = false
Power Channel 7 - Name                              = Valve 7
Power Channel 7 - State                             = false
Power Channel 8 - Name                              = Valve 8
Power Channel 8 - State                             = false
Power Channel 9 - Name                              = Valve 9
Power Channel 9 - State                             = false
Power Channel 10 - Name                             = Valve 10
Power Channel 10 - State                            = false
Output Data Rate                                    = 1
