############################################################################
# Copyright 2007-2026 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################

[Payload.RedX]
Enabled                                                         = Always
Active                                                          = false
Entity Label                                                    = RedX Payload
Debug Level                                                     = None
Activation Time                                                 = 5
Deactivation Time                                               = 5
Entity Label for Depth Information                              = Power Simulator
Power Channel Control - Descend Motor                           = DescendBombMotor
Power Channel Control - Bomb in Water                           = BombInWater
Power Channel Control - Bomb in Tank                            = BombInTank
Power Channel Control - Sensor Water Tank Maximum               = SensorWaterTankMax
Power Channel Control - Sensor Water Tank Minimum               = SensorWaterTankMin
Power Channel Control - Purge Valve Extern                      = PurgeValveExt
Power Channel Control - Valve Filter 1                          = ValveFilter1
Power Channel Control - Valve Filter 2                          = ValveFilter2
Power Channel Control - Valve Filter 3                          = ValveFilter3
Power Channel Control - Valve Filter 4                          = ValveFilter4
Power Channel Control - Valve Filter 5                          = ValveFilter5
Power Channel Control - Valve Filter 6                          = ValveFilter6
Power Channel Control - Valve Filter 7                          = ValveFilter7
Power Channel Control - Valve Filter 8                          = ValveFilter8
Power Channel Control - Valve Filter 9                          = ValveFilter9
Power Channel Control - Sensor Filter Fill Up                   = SensorFillUpFilter
Number of Filters to use                                        = 9
Maximum Time to wait for a filter to fill up                    = 60.0
Maximum Time to wait for a purge valve to open/close            = 10.0
Depth to put the water bomb in water at when descending         = 0.5

