//***************************************************************************
// Copyright 2007-2019 Universidade do Porto - Faculdade de Engenharia      *
// Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  *
//***************************************************************************
// This file is part of DUNE: Unified Navigation Environment.               *
//                                                                          *
// Commercial Licence Usage                                                 *
// Licencees holding valid commercial DUNE licences may use this file in    *
// accordance with the commercial licence agreement provided with the       *
// Software or, alternatively, in accordance with the terms contained in a  *
// written agreement between you and Faculdade de Engenharia da             *
// Universidade do Porto. For licensing terms, conditions, and further      *
// information contact lsts@fe.up.pt.                                       *
//                                                                          *
// Modified European Union Public Licence - EUPL v.1.1 Usage                *
// Alternatively, this file may be used under the terms of the Modified     *
// EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md *
// included in the packaging of this file. You may not use this work        *
// except in compliance with the Licence. Unless required by applicable     *
// law or agreed to in writing, software distributed under the Licence is   *
// distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     *
// ANY KIND, either express or implied. See the Licence for the specific    *
// language governing permissions and limitations at                        *
// https://github.com/LSTS/dune/blob/master/LICENCE.md and                  *
// http://ec.europa.eu/idabc/eupl.html.                                     *
//***************************************************************************
// Author: Pedro Calado                                                     *
//***************************************************************************

// ISO C++ 98 headers.
#include <iomanip>

// DUNE headers.
#include <DUNE/DUNE.hpp>

// Local headers.
#include "QuadTree.hpp"

using DUNE_NAMESPACES;

namespace Simulators
{
  //! CTD (Conductivity, Temperature, Depth) sensor simulator.
  //! All data is generated using a mean and standard deviation.
  //!
  //! The depth value is generated by listening to DUNE::IMC::SimulatedState
  //! and applying a standard deviation to received values.
  namespace CTD
  {

    //! %Task arguments.
    struct Arguments
    {
      //! Where temperature data was taken from.
      std::string location;
      //! Standard deviation of temperature measurements.
      double std_dev_temp;
      //! Mean temperature value.
      float mean_temp;
      //! Out of bounds temperature value.
      float oob_temp;
      //! Tide level (m).
      float tide_level;
      //! Standard deviation of conductivity measurements.
      double std_dev_cond;
      //! Mean conductivity value.
      float mean_cond;
      //! Standard deviation of depth measurements.
      double std_dev_depth;
      //! Name of Pseudo-Random Number Generator to use.
      std::string prng_type;
      //! PRNG seed.
      int prng_seed;
    };

    //! %SVS simulator task.
    struct Task: public Tasks::Periodic
    {
      //! Temperature.
      IMC::Temperature m_temp;
      //! Current sound speed.
      IMC::SoundSpeed m_sspeed;
      //! Current conductivity.
      IMC::Conductivity m_cond;
      //! Current salinity.
      IMC::Salinity m_salinity;
      IMC::Depth m_depth;
      IMC::Pressure m_pressure;
      //! Last received simulated state.
      IMC::SimulatedState m_sstate;
      //! PRNG handle.
      Random::Generator* m_prng;
      //! Reference latitude and longitude for data points.
      double m_ref_lat, m_ref_lon;
      //! NE offsets in regard to navigational reference.
      double m_off_n, m_off_e;
      //! The tree.
      QuadTree* m_qtree;
      //! Task arguments.
      Arguments m_args;

      Task(const std::string& name, Tasks::Context& ctx):
        Tasks::Periodic(name, ctx),
        m_prng(NULL),
        m_qtree(NULL)
      {
        // Retrieve configuration values.
        param("Location", m_args.location)
        .defaultValue("Data");

        param("Standard Deviation - Temperature", m_args.std_dev_temp)
        .defaultValue("1.0");

        param("Mean Value - Temperature", m_args.mean_temp)
        .defaultValue("14.0");

        param("Out Of Bounds Temperature", m_args.oob_temp)
        .defaultValue("5.0");

        param("Tide Level", m_args.tide_level)
        .defaultValue("0.0");

        param("Standard Deviation - Conductivity", m_args.std_dev_cond)
        .defaultValue("1.0");

        param("Mean Value - Conductivity", m_args.mean_cond)
        .defaultValue("4.0");

        param("Standard Deviation - Depth", m_args.std_dev_depth)
        .defaultValue("0.1");

        param("PRNG Type", m_args.prng_type)
        .description("Pseudo-Random Number Generator type. Examples: \"c_fsr256\", \"krng\"")
        .defaultValue(Random::Factory::c_default);

        param("PRNG Seed", m_args.prng_seed)
        .description("Random seed to use to random generator.")
        .defaultValue("-1");

        // Register consumers.
        bind<IMC::GpsFix>(this);
        bind<IMC::SimulatedState>(this);
      }

      //! Initialize resources. It requests deactivation so that this task
      //! is not active by default and will be activated only when
      //! DUNE::IMC::SimulatedState messages are received.
      void
      onResourceInitialization(void)
      {
        Utils::String::toLowerCase(m_args.location);
        Path path = m_ctx.dir_cfg / "simulation" / ("temperature-"+ m_args.location +".ini");
        DUNE::Parsers::Config cfg(path.c_str());
        std::vector<std::string> lines;
        cfg.get("Temperature", "Data", "", lines);
        cfg.get("Temperature", "Latitude (degrees)", "", m_ref_lat);
        cfg.get("Temperature", "Longitude (degrees)", "", m_ref_lon);

        //Convert angular coordinates from degrees to radians
        m_ref_lat = Angles::radians(m_ref_lat);
        m_ref_lon = Angles::radians(m_ref_lon);


        //Auxiliary objects to fill qtree
        std::vector<QuadTree::Item> data;
        QuadTree::Item item;
        Bounds* bounds = 0;

        //Set data points
        for(unsigned i = 0; i < lines.size(); ++i)
        {
          //Get individual fields
          std::vector<std::string> v;
          DUNE::Utils::String::split(lines[i], " ", v);

          //Set x and y
          std::stringstream sin(v[0]);
          sin >> item.x;
          sin.clear();
          sin.str(v[1]);
          sin >> item.y;

          //Set data values
          //Read all data values after x,y (the first 2)
          for(unsigned it = 0; it<v.size()-2; ++it)
          {
            sin.clear();
            sin.str(v[it+2].compare("nan") != 0 ? v[it+2] : "-999");
            sin >> item.value[it];
          }
          data.push_back(item);

          //Expand bounds
          if (!bounds)
            bounds = new Bounds(Point(item.x, item.y));
          else
            bounds->cover(Point(item.x, item.y));

          sin.clear();
        }

        // Fill the tree
        m_qtree = new QuadTree(*bounds);
        delete bounds;

        for (unsigned i = 0; i < data.size(); ++i)
          m_qtree->insert(data[i]);

        requestDeactivation();
      }

      //! Acquire resources. Initializes the random number generator
      void
      onResourceAcquisition(void)
      {
        //! Initialize the random number generator.
        m_prng = Random::Factory::create(m_args.prng_type, m_args.prng_seed);
      }

      //! Release resources.
      void
      onResourceRelease(void)
      {
        Memory::clear(m_prng);
        Memory::clear(m_qtree);
      }

      //! Calculates offset between data and GPS reference origins
      //! for referential convertion ((OFF) = (GPS) - (BAT))
      void
      consume(const IMC::GpsFix* msg)
      {
        if (msg->type != IMC::GpsFix::GFT_MANUAL_INPUT)
          return;

        // Get offsets for data
        //(m_off_n, m_off_e) = (GPS_offset)-(DATA_offset)
        WGS84::displacement(m_ref_lat, m_ref_lon, 0, msg->lat, msg->lon, 0,
                            &m_off_n, &m_off_e);
      }

      //! Requests activation of the task (if not active already) and stores
      //! received state in #m_sstate.
      void
      consume(const IMC::SimulatedState* msg)
      {
        if (!isActive())
        {
          setEntityState(IMC::EntityState::ESTA_NORMAL, Status::CODE_ACTIVE);
          requestActivation();
        }
        m_sstate = *msg;
      }

      //! If active, computes all values using random value generators and dispatches:
      //! * @publish DUNE::IMC::Temperature
      //! * @publish DUNE::IMC::Salinity
      //! * @publish DUNE::IMC::Depth
      //! * @publish DUNE::IMC::Conductivity
      //! * @publish DUNE::IMC::SoundSpeed
      //! * @publish DUNE::IMC::Pressure
      void
      task(void)
      {
        // Return if task is not active.
        if (!isActive())
          return;

        m_temp.setTimeStamp();
        m_temp.value = temperatureAt(m_sstate.x + m_off_n, m_sstate.y + m_off_e, m_sstate.z);
        m_temp.value = m_temp.value + m_prng->gaussian() * m_args.std_dev_temp;

        m_cond.setTimeStamp(m_temp.getTimeStamp());
        m_cond.value = m_args.mean_cond + m_prng->gaussian() * m_args.std_dev_cond;

        m_depth.setTimeStamp(m_temp.getTimeStamp());
        m_depth.value = std::max(m_sstate.z + m_prng->gaussian() * m_args.std_dev_depth, 0.0);

        // Compute pressure.
        m_pressure.setTimeStamp(m_temp.getTimeStamp());
        m_pressure.value = (m_depth.value * c_gravity * c_seawater_density + c_sea_level_pressure) / c_pascal_per_bar;

        m_salinity.setTimeStamp(m_temp.getTimeStamp());
        m_salinity.value = UNESCO1983::computeSalinity(m_cond.value, m_pressure.value, m_temp.value);

        m_sspeed.setTimeStamp(m_temp.getTimeStamp());
        m_sspeed.value = (m_salinity.value < 0.0) ? -1.0 : UNESCO1983::computeSoundSpeed(m_salinity.value, m_pressure.value, m_temp.value);

        dispatch(m_temp, DF_KEEP_TIME);
        dispatch(m_cond, DF_KEEP_TIME);
        dispatch(m_depth, DF_KEEP_TIME);
        dispatch(m_pressure, DF_KEEP_TIME);
        dispatch(m_salinity, DF_KEEP_TIME);
        dispatch(m_sspeed, DF_KEEP_TIME);
      }

      double
      temperatureAt(double x, double y, double z)
      {
        Point p(x, y);
        Bounds search_area(p, 10);

        std::vector<QuadTree::Item> items;
        m_qtree->search(search_area, items);

        if (items.size() == 0)
        {
          trace("out of bounds");
          return m_args.oob_temp;//m_args.oob_depth
        }

        trace("found %lu close data values", (long unsigned int)items.size());

        // @todo interpolate rather than picking closest one
        double dmin = p.distance(Point(items[0].x, items[0].y));
        unsigned value_index = int((z - m_args.tide_level)/3);
        double temp = items[0].value[value_index];

        for (unsigned int i = 1; i < items.size(); ++i)
        {
          double d = p.distance(Point(items[i].x, items[i].y));
          if (d < dmin)
          {
            dmin = d;
            temp = items[i].value[value_index];
          }
        }

        return temp;
      }
    };
  }
}

DUNE_TASK
