if(BTCPP)
  # Try a system package first.
  find_package(behaviourtree_cpp QUIET)

  if(behaviourtree_cpp_FOUND)
    dune_add_lib(behaviourtree_cpp)
    add_definitions(-DDUNE_BTCPP_ENABLED)
    set(DUNE_USING_BTCPP 1 CACHE INTERNAL "BehaviourTree.CPP support")
  elseif(EXISTS "${PROJECT_SOURCE_DIR}/vendor/libraries/BehaviorTree.CPP/CMakeLists.txt")
    message(STATUS "behaviourtree_cpp package not found; building bundled BehaviorTree.CPP from vendor/libraries/BehaviorTree.CPP.")
    add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/libraries/BehaviorTree.CPP" "${CMAKE_BINARY_DIR}/vendor/BehaviorTree.CPP" EXCLUDE_FROM_ALL)
    dune_add_lib(behaviortree_cpp)
    add_definitions(-DDUNE_BTCPP_ENABLED)
    set(DUNE_VENDOR_INCS_DIR ${DUNE_VENDOR_INCS_DIR} ${PROJECT_SOURCE_DIR}/vendor/libraries/BehaviorTree.CPP/include)
    set(DUNE_USING_BTCPP 1 CACHE INTERNAL "BehaviourTree.CPP support")
  else()
    message(SEND_ERROR "BehaviourTree.CPP support requested (BTCPP=ON), but behaviourtree_cpp package was not found.\n  - To disable: -DBTCPP=OFF\n  - To install: install behaviourtree_cpp and set behaviourtree_cpp_DIR or CMAKE_PREFIX_PATH.")
    set(DUNE_USING_BTCPP 0 CACHE INTERNAL "BehaviourTree.CPP support")
  endif()
endif(BTCPP)
