if(DUNE_SYS_HAS_DCCL AND DUNE_SYS_HAS_PROTOBUF)
  file(TO_NATIVE_PATH ${CMAKE_CURRENT_LIST_DIR}/Proto PROTOMODEL_PATH) 
  file(TO_NATIVE_PATH ${CMAKE_CURRENT_LIST_DIR} PROTOBINDING_PATH)
  file(GLOB DATAMODEL_PROTOS "${CMAKE_CURRENT_LIST_DIR}/Proto/*.proto")
  foreach(proto ${DATAMODEL_PROTOS})
    file(TO_NATIVE_PATH ${proto} proto_native)
    #execute_process(COMMAND "/usr/local/include" --proto_path=${PROTOMODEL_PATH}  --cpp_out=${PROTOBINDING_PATH} ${proto_native} RESULT_VARIABLE rv)
    execute_process(COMMAND ${Protobuf_PROTOC_EXECUTABLE} --proto_path=${PROTOMODEL_PATH} --proto_path=/usr/local/include --cpp_out=${PROTOBINDING_PATH} ${proto_native} RESULT_VARIABLE rv)
    #oss: /usr/local/include if this is the exact location of this file IMC_DCCL_Converter.cpp
    #qui ci sara riga che genere automaticamente 
    if(${rv})
      message(SEND_ERROR "Generation of data model returned ${rv} for proto ${proto_native}")
    endif()
  endforeach(proto)
else(DUNE_SYS_HAS_DCCL AND DUNE_SYS_HAS_PROTOBUF)
  set(TASK_ENABLED FALSE)
endif(DUNE_SYS_HAS_DCCL AND DUNE_SYS_HAS_PROTOBUF)